# Generated by Django 5.2 on 2025-09-29 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_run', '0005_alter_athleteinfo_weight'),
    ]

    operations = [
        migrations.AlterField(
            model_name='athleteinfo',
            name='goals',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='athleteinfo',
            name='weight',
            field=models.IntegerField(null=True),
        ),
    ]
