# Generated by Django 5.2 on 2025-10-07 15:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_run', '0007_challenge'),
    ]

    operations = [
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('run_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='positions', to='app_run.run')),
            ],
        ),
    ]
