# Generated by Django 5.2 on 2025-10-08 16:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_run', '0008_position'),
    ]

    operations = [
        migrations.RenameField(
            model_name='position',
            old_name='run_id',
            new_name='run',
        ),
    ]
