# Generated by Django 5.2 on 2025-10-09 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_run', '0009_rename_run_id_position_run'),
    ]

    operations = [
        migrations.AddField(
            model_name='run',
            name='distance',
            field=models.FloatField(null=True),
        ),
    ]
