# Generated by Django 5.2 on 2025-10-17 15:36

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_run', '0011_collectibleitem'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='collectibleitem',
            name='collitems',
            field=models.ManyToManyField(blank=True, related_name='collectibleitems', to=settings.AUTH_USER_MODEL),
        ),
    ]
