# Generated by Django 5.2 on 2025-10-18 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_run', '0012_collectibleitem_collitems'),
    ]

    operations = [
        migrations.AddField(
            model_name='position',
            name='date_time',
            field=models.DateTimeField(null=True),
        ),
    ]
