# Generated by Django 5.2 on 2025-10-28 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_run', '0015_alter_run_run_time_seconds'),
    ]

    operations = [
        migrations.AddField(
            model_name='position',
            name='distance',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='position',
            name='speed',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='run',
            name='speed',
            field=models.FloatField(null=True),
        ),
    ]
